version: "2"

formatters:
  enable:
    - gofmt
    - goimports
    - golines

linters:
  default: "all"
  disable:
    - revive
    - exhaustruct
    - ireturn
    - varnamelen
    - gomoddirectives
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/viqueen/buf-template
            - gorm.io/driver/postgres
            - gorm.io/gorm
            - connectrpc.com/connect
            - connectrpc.com/cors
            - connectrpc.com/otelconnect
            - github.com/gofrs/uuid
            - golang.org/x/net/http2
            - golang.org/x/net/http2/h2c
            - github.com/rs/cors
            - github.com/rs/zerolog